[Variables]

Bands=19
; Number of peaks - Activate Ocean\GenerateBands.ini skin after changing this value

Color=63,143,101

Width=1280
Height=310

LineWidth=3

AverageSize=1
; Average sound levels over time to provide continuity

LoudnessEqualization=1
; Increases visibility for quiet audio sources when applicable

FFTSize=10240
FFTOverlap="(#FFTSize#-256)"
FFTAttack=345
FFTDecay=485
FreqMin=22
FreqMax=11760
Sensitivity=18
; http://docs.rainmeter.net/manual-beta/plugins/audiolevel

MusicPlayer=None
; Music player process name

FirstBandIndex=1

; Environment variables for settings window
SkinGroup=Ocean
Config=Ocean
ConfigPath=C:\Users\Admin\Documents\Rainmeter\Skins\Ocean\Ocean.ini
WriteVariable=Color
LineOnly=0
Angle=0
Invert=0
Channel=Avg
Port=Output
ID=
